services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    env_file: .env
    restart: unless-stopped
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: 2001:db8:2::/64