name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build API image
      run: docker build forge-backend --file forge-backend/Dockerfile.api --tag forge-api:$(date +%s)
    
    - name: Build Worker image
      run: docker build forge-backend --file forge-backend/Dockerfile.worker --tag forge-worker:$(date +%s)
